# Generated by Django 5.1.1 on 2024-10-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
