# Generated by Django 5.1.1 on 2024-10-21 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_searchhistory_search_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_region',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_results',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_query',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
