# Generated by Django 5.1.2 on 2024-10-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_resume_email_alter_resume_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school_name',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='company_name',
            new_name='role',
        ),
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='app.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_set', to='app.resume'),
        ),
    ]
