# Generated by Django 5.1.2 on 2024-10-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_school_name_education_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume'),
        ),
    ]
