# Generated by Django 5.1.2 on 2024-10-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_education_major_alter_education_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
