# Generated by Django 5.1.2 on 2024-10-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_resume_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
