# Generated by Django 5.1.2 on 2024-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_education_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
