# Generated by Django 5.1.2 on 2024-10-23 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_education_grade_alter_education_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='preferred_industries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
                ('issuing_agency', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
    ]
