# Generated by Django 5.1.2 on 2024-10-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_resume_preferred_industries_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
