# Generated by Django 5.1.2 on 2024-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='detailed_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
